[package]
name = "pet-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging
log = "0.4.17"
log4rs = "1.1.1"

# Web
rocket = "0.5.0-rc.2"